plugins {
    id 'io.nextflow.nextflow-plugin' version '1.0.0-beta.10'
}

version = '1.0.1'

nextflowPlugin {
    nextflowVersion = '24.10.0'
    provider = 'Fulcrum Genomics'
    className = 'nextflow.fgbio.FgbioPlugin'
    extensionPoints = [
        'nextflow.fgbio.FgbioExtension'
    ]
}

dependencies {
    implementation 'com.fulcrumgenomics:fgbio_2.13:2.5.21'
}
